# Generated by Django 5.0.6 on 2024-06-29 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('task_type', models.CharField(choices=[('Ремонт', 'Ремонт'), ('Покупки', 'Покупки'), ('Уборка', 'Уборка'), ('Слушатель', 'Слушатель'), ('Другое', 'Другое')], max_length=50, verbose_name='Тип задания')),
                ('preferred_gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Не важно', 'Не важно')], max_length=20, verbose_name='Предпочитаемый пол')),
                ('urgency', models.CharField(choices=[('Срочно', 'Срочно'), ('Не особо срочно', 'Не особо срочно'), ('Выбор времени', 'Выбор времени')], max_length=50, verbose_name='Срочность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
